version: "3"
services:
  web:
    build:
      context: ./flask-support
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5005:5000"
    depends_on:
      - redis
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  beat:
    build:
      context: celery-beat
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc1